name: All build

on: [push, pull_request]

jobs:
  build-windows-release:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install conan
        id: conan
        uses: turtlebrowser/get-conan@main

      - name: Conan version
        run: echo "${{steps.conan.outputs.version}}"

      - name: Create profile
        run: conan profile detect --name sip

      - name: Update profile
        run: (Get-Content $(conan profile path sip)) -replace 'compiler.cppstd=.*', 'compiler.cppstd=23' | Set-Content $(conan profile path sip)

      - name: Show conan profile
        run: conan profile show --profile:build=sip --profile:host=sip

      - name: Install relese dependencies
        run: conan install ${{github.workspace}} --output-folder=${{github.workspace}}/build --build=missing -pr:h=sip -pr:b=sip

      - name: Configure CMake
        run: cmake --preset conan-default

      - name: Build release
        run: cmake --build --preset conan-release

      - name: Test release
        run: ctest --preset conan-release --output-on-failure

  build-windows-debug:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install conan
        id: conan
        uses: turtlebrowser/get-conan@main

      - name: Conan version
        run: echo "${{steps.conan.outputs.version}}"

      - name: Create profile
        run: conan profile detect --name sip

      - name: Update profile
        run: (Get-Content $(conan profile path sip)) -replace 'compiler.cppstd=.*', 'compiler.cppstd=23' | Set-Content $(conan profile path sip)

      - name: Show conan profile
        run: conan profile show --profile:build=sip --profile:host=sip

      - name: Install relese dependencies
        run: conan install ${{github.workspace}} --output-folder=${{github.workspace}}/build --build=missing -pr:h=sip -pr:b=sip -s build_type=Debug

      - name: Configure CMake
        run: cmake --preset conan-default

      - name: Build debug
        run: cmake --build --preset conan-debug

      - name: Test debug
        run: ctest --preset conan-debug --output-on-failure

  build-linux-clang-release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Update source
        run: sudo sed -i 's/jammy/lunar/g' '/etc/apt/sources.list' && echo "deb http://apt.llvm.org/lunar/ llvm-toolchain-lunar-16 main" | sudo tee -a /etc/apt/sources.list && wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key | sudo apt-key add - && sudo apt update

      - name: Install clang
        run: sudo apt install -y clang-16

      - name: Install conan
        id: conan
        uses: turtlebrowser/get-conan@main

      - name: Conan version
        run: echo "${{steps.conan.outputs.version}}"

      - name: Create profile
        run: conan profile detect --name sip

      - name: Update standard in conan profile
        run: sed -i 's/compiler.cppstd=.*/compiler.cppstd=23/' $(conan profile path sip)

      - name: Update compiler in conan profile
        run: sed -i 's/compiler=.*/compiler=clang/' $(conan profile path sip)

      - name: Update compiler version in conan profile
        run: sed -i 's/compiler.version=.*/compiler.version=16/' $(conan profile path sip) && echo -e "[buildenv]\nCC=clang-16\nCXX=clang++-16" >> $(conan profile path sip)

      - name: Show conan profile
        run: conan profile show --profile:build=sip --profile:host=sip

      - name: Install relese dependencies
        run: conan install ${{github.workspace}} --output-folder=${{github.workspace}}/build --build=missing -pr:h=sip -pr:b=sip

      - name: Configure CMake
        run: CC=clang-16 CXX=clang++-16 cmake --preset conan-release

      - name: Build release
        run: cmake --build --preset conan-release

      - name: Test release
        run: ctest --preset conan-release --output-on-failure

  build-linux-clang-debug:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Update source
        run: sudo sed -i 's/jammy/lunar/g' '/etc/apt/sources.list' && echo "deb http://apt.llvm.org/lunar/ llvm-toolchain-lunar-16 main" | sudo tee -a /etc/apt/sources.list && wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key | sudo apt-key add - && sudo apt update

      - name: Install clang
        run: sudo apt install -y clang-16

      - name: Install conan
        id: conan
        uses: turtlebrowser/get-conan@main

      - name: Conan version
        run: echo "${{steps.conan.outputs.version}}"

      - name: Create profile
        run: conan profile detect --name sip

      - name: Update standard in conan profile
        run: sed -i 's/compiler.cppstd=.*/compiler.cppstd=23/' $(conan profile path sip)

      - name: Update compiler in conan profile
        run: sed -i 's/compiler=.*/compiler=clang/' $(conan profile path sip)

      - name: Update compiler version in conan profile
        run: sed -i 's/compiler.version=.*/compiler.version=16/' $(conan profile path sip) && echo -e "[buildenv]\nCC=clang-16\nCXX=clang++-16" >> $(conan profile path sip)

      - name: Show conan profile
        run: conan profile show --profile:build=sip --profile:host=sip

      - name: Install relese dependencies
        run: conan install ${{github.workspace}} --output-folder=${{github.workspace}}/build --build=missing -pr:h=sip -pr:b=sip -s build_type=Debug

      - name: Configure CMake
        run: CC=clang-16 CXX=clang++-16 cmake --preset conan-debug

      - name: Build debug
        run: cmake --build --preset conan-debug

      - name: Test debug
        run: ctest --preset conan-debug --output-on-failure

  build-linux-gcc-release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Update source
        run: sudo sed -i 's/jammy/lunar/g' '/etc/apt/sources.list' && sudo apt update

      - name: Install gcc 13
        run: sudo apt install -y  gcc-13 g++-13

      - name: Install conan
        id: conan
        uses: turtlebrowser/get-conan@main

      - name: Conan version
        run: echo "${{steps.conan.outputs.version}}"

      - name: Create profile
        run: conan profile detect --name sip

      - name: Update standard in conan profile
        run: sed -i 's/compiler.cppstd=.*/compiler.cppstd=23/' $(conan profile path sip)

      - name: Update compiler in conan profile
        run: sed -i 's/compiler=.*/compiler=gcc/' $(conan profile path sip)

      - name: Update compiler version in conan profile
        run: sed -i 's/compiler.version=.*/compiler.version=12.2/' $(conan profile path sip) && echo -e "[buildenv]\nCC=gcc-13\nCXX=g++-13" >> $(conan profile path sip)

      - name: Show conan profile
        run: conan profile show --profile:build=sip --profile:host=sip

      - name: Install relese dependencies
        run: conan install ${{github.workspace}} --output-folder=${{github.workspace}}/build --build=missing -pr:h=sip -pr:b=sip

      - name: Configure CMake
        run: cmake --preset conan-release

      - name: Build release
        run: cmake --build --preset conan-release

      - name: Test release
        run: ctest --preset conan-release --output-on-failure

  build-linux-gcc-debug:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Update source
        run: sudo sed -i 's/jammy/lunar/g' '/etc/apt/sources.list' && sudo apt update

      - name: Install gcc 13
        run: sudo apt install -y  gcc-13 g++-13

      - name: Install conan
        id: conan
        uses: turtlebrowser/get-conan@main

      - name: Conan version
        run: echo "${{steps.conan.outputs.version}}"

      - name: Create profile
        run: conan profile detect --name sip

      - name: Update standard in conan profile
        run: sed -i 's/compiler.cppstd=.*/compiler.cppstd=23/' $(conan profile path sip)

      - name: Update compiler in conan profile
        run: sed -i 's/compiler=.*/compiler=gcc/' $(conan profile path sip)

      - name: Update compiler version in conan profile
        run: sed -i 's/compiler.version=.*/compiler.version=12.2/' $(conan profile path sip) && echo -e "[buildenv]\nCC=gcc-13\nCXX=g++-13" >> $(conan profile path sip)

      - name: Show conan profile
        run: conan profile show --profile:build=sip --profile:host=sip

      - name: Install relese dependencies
        run: conan install ${{github.workspace}} --output-folder=${{github.workspace}}/build --build=missing -pr:h=sip -pr:b=sip -s build_type=Debug

      - name: Configure CMake
        run: cmake --preset conan-debug

      - name: Build debug
        run: cmake --build --preset conan-debug

      - name: Test debug
        run: ctest --preset conan-debug --output-on-failure
